CREATE TABLE IF NOT EXISTS user_roles(
    id integer primary key generated by default as identity,
    role_name varchar(15),
    description varchar(100)
);

CREATE TABLE IF NOT EXISTS actions(
    id integer primary key generated by default as identity,
    action_name varchar(15),
    description varchar(100)
);

CREATE TABLE IF NOT EXISTS property(
    id integer primary key generated by default as identity,
    house_number integer NOT NULL,
    home_owner_name varchar(100)
);

CREATE TABLE IF NOT EXISTS users(
    id integer primary key generated by default as identity,
    phone_number bigint NOT NULL,
    user_role_id integer NOT NULL,
    property_id integer NOT NULL,
    foreign key (property_id) references property(id),
    foreign key (user_role_id) references user_roles(id)
);

CREATE TABLE IF NOT EXISTS history(
    id uuid default gen_random_uuid(),
    property_id integer,
    user_id integer,
    event_date varchar(15) NOT NULL,
    event_time timestamp default current_timestamp,
    gate_msg_tn bigint,
    gate_msg_text varchar(1000),
    action_id integer NOT NULL,
    primary key (id, event_date),
    foreign key (property_id) references property(id),
    foreign key (user_id) references users(id),
    foreign key (action_id) references actions(id)
) partition by list(event_date);

